# Generated by Django 4.2.6 on 2024-05-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='listmovie')),
                ('year', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('link', models.URLField(max_length=250)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.cat_movie')),
            ],
        ),
    ]
